# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
executors:
  jdk-executor:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  build:
    context: blackduck
    working_directory: ~/build
    executor: jdk-executor
    steps:
      - checkout
      - run:
          name: Run Blackduck Detect
          command: |
            ./synopsys-detect \
            ci-build DACH-NY_security-blackduck master \
            --logging.level.com.synopsys.integration=DEBUG

