name: Blackduck

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

#      - name: Run Blackduck Detect
#        run: |
#          ./synopsys-detect \
#            ci-build DACH-NY_security-blackduck master \
#            --logging.level.com.synopsys.integration=DEBUG